### ISSUE TITLE
No results found, due to conf file errors

### ISSUE THREAD

**Issue by stax76** [Seme4eg/mpv-scripts#3]
If I search for something common like `set`, `add` or `cycle`, which is used very often in my bindings, it's not finding anything. If I empty the search field, it shows all my 302 bindings.

![Screenshot from 2022-11-22 16-25-47](https://user-images.githubusercontent.com/11410540/203353426-d40a7714-7ee1-4ea4-a692-d449de357424.png)

**Comment by Seme4eg** [comment]
I'll copy paste a section of a documentation here, maybe that's the case why those don't appear for you:

NOTE: For script commands to appear in leader key bindings (after you set those up in script file) they must be initially set to some key, which is usually not a problem since most (if not all) scripts bind themselfes to some default key

**Comment by stax76** [comment]
The problem is caused by the conf file, without conf file it works fine. On the terminal, it shows:

```
[M_x] Error: Can't convert '65 # strip cmd name' to number! 
[M_x] script-opts/M_x.conf:2 error converting value '65 # strip cmd name' for key 'strip_cmd_at' 
[M_x] script-opts/M_x.conf:3 unknown key 'sort_commands_by ', ignoring 
[M_x] Error: Can't convert 'true' to boolean! 
[M_x] script-opts/M_x.conf:8 error converting value 'true' for key 'pause_on_open' 
Exiting... (Quit)
```

There is an error in the Readme:

`~~/scripts-opts/M-x.conf`

It should be `M_x.conf`.

**Comment by Seme4eg** [comment]
there are many errors in my conf file example:
- you are not allowed for comments in the end of the line
- values 'true/false' in conf file are 'yes/no'

**Comment by Seme4eg** [comment]
hopefully fixed now, you can check and if it is then close the issue please
