### ISSUE TITLE
Problem font rendering

### ISSUE THREAD

**Issue by stax76** [Seme4eg/mpv-scripts#4]
I propose an option to disable the column layout and put the comment directly after the binding without spacing.

![Screenshot from 2022-11-25 06-11-43](https://user-images.githubusercontent.com/11410540/203906153-d1c51c24-0546-4df4-a314-f0f9aaa6ebe0.png)

**Comment by Seme4eg** [comment]
If you don't mind I'ma wait with removing this feature until some more people will agree with your proposal. Since some may say afterwards that it made the readability worse.

**Comment by stax76** [comment]
I meant making it optional via conf option, doesn't matter to me what the default is. I wonder why you are not getting this problem. Which OS do you use? Maybe we can estimate how likely it is users getting this problem. I can try Windows 11 since I have it installed.

**Comment by stax76** [comment]
I tried it on Windows 11 (300% Zoom) in mpv.net, there it's also not properly aligned, should be the same in mpv.

**Comment by stax76** [comment]
Is there maybe a good monospaced font I can try to install?

**Comment by Cananbolt** [comment]
> If you don't mind I'ma wait with removing this feature until some more people will agree with your proposal. Since some may say afterwards that it made the readability worse.

I like this proposal.  Some of the text is cutting out on my screen.

**Comment by Seme4eg** [comment]
i think this issue was resolved with @stax76 pull request #5
