### ISSUE TITLE
Caret/Cursor of input search field is too thin in High DPI environment

### ISSUE THREAD

**Issue by stax76** [Seme4eg/mpv-scripts#6]
A screenshot can be found here:

https://github.com/Seme4eg/mpv-scripts/issues/4

In the built-in on screen console, it's fine.

**Comment by stax76** [comment]
Could you make an option?

`cursor_x_border = 0.3, -- cursor width`

`'\\xbord' .. self.cursor_x_border .. '\\p4\\pbo24}' .. -- xborder, scale x8 and baseline offset`

For me, using 300 % zoom, 0.9 looks best.

**Comment by Seme4eg** [comment]
I sure will
But now I'm in kind of a life mess, hopefully during this month I will be able to just sit and address all the issues I currently have on this little repo.
Sorry for the delay

**Comment by stax76** [comment]
Good luck with the life situation.

**Comment by Seme4eg** [comment]
done
