### ISSUE TITLE
script-ops not working

### ISSUE THREAD

**Issue by darkdream787** [Seme4eg/mpv-scripts#8]
I have tried to set the key be "c" in the .conf file, but it does not work. The player says "No key binding found for key c".

No matter what I try, nothing I do to that .conf file is having any effect.

It works if I edit the .lua file, but the .lua file says "-- should not be altered here, edit options in corresponding .conf file". 
Why is the .conf file having no effect?

strip_cmd_at=65 # strip cmd name
sort_commands_by = 'priority', # available values: priority, command_name

#- options for extended menu ------------------------------------------------
toggle_menu_binding=c
lines_to_show=17
pause_on_open=true
resume_on_exit=only-if-was-paused # another possible value is true

#- styles
font_size=21
line_bottom_margin=1
menu_x_padding=5
menu_y_padding=2

search_heading=M-x # heading text of a search bar
filter_by_fields=[ "cmd", "key", "comment" ] # look for explanation below
column_layout=no

**Comment by Seme4eg** [comment]
lines like
`strip_cmd_at=65 # strip cmd name` are not valid format for conf files, it doesn't read lines that end with comments
also lines like `sort_commands_by = 'priority'` are invalid, there should be no spaces around '=' sign.
Other than that i don't know what might be the reason, my .conf file for M-x script is in `~/.config/mpv/script-opts/M_x.conf`; Make sure it's called exactly `M_x.conf`
