### ISSUE TITLE
Something is off in `get_line` func

### ISSUE THREAD

**Issue by magnetophon** [Seme4eg/mpv-scripts#9]
Thanks for this wonderful plugin.

When I start an empty mpv config, and follow the readme for ``M-x``, then open mpv and hit ``t``, I get a menu full of the above error.
The filtering and execution of commands works as expected, I just can't see what I'm doing!  :)

![image](https://github.com/Seme4eg/mpv-scripts/assets/7645711/a07f6ec8-8e19-44f8-86a2-fad4fc9e07df)

**Comment by Kabouik** [comment]
I've got the same issue.

**Comment by magnetophon** [comment]
FWIW: https://github.com/stax76/mpv-scripts#command_palette works nicely and has a few other useful modes as well, for example one for selecting chapters in the video.

**Comment by Seme4eg** [comment]
just saw the issue, sorry, i'll look into it asap
haven't been using that plugin since i switched to its 'rofi' version

**Comment by Seme4eg** [comment]
fixed!

**Comment by magnetophon** [comment]
Thanks, all good now!
